export const LIBERA_ACESSO = 'LIBERA_ACESSO';
export const PEGA_EVENTO = 'PEGA_EVENTO';
export const PEGAR_TODOS_EVENTOS = 'PEGA_TODOS_EVENTOS';
export const CADASTRA_EVENTO = 'CADASTRA_EVENTO';
export const RESETA_EVENTO = 'RESETA_EVENTO';
export const DELETE_EVENTO = 'DELETE_EVENTO';
export const PEGA_TODOS_DADOS = 'PEGA_TODOS_DADOS';